#!/usr/bin/env python3
"""snarkjs (vkey.json, proof.json, public.json) -> groth16-solana byte layout.
Writes <out>.json (hex fixture) and, with --vk-rs, the Rust vk.rs for fs_kyc_spike.
usage: convert_snarkjs.py vkey.json proof.json public.json out.json [--vk-rs path]"""
import json, sys
P = 21888242871839275222246405745257275088696311157297823662689037894645226208583
vk = json.load(open(sys.argv[1])); pr = json.load(open(sys.argv[2])); pub = json.load(open(sys.argv[3]))
be = lambda v: int(v).to_bytes(32, "big")
g1 = lambda p: be(p[0]) + be(p[1])
g2 = lambda p: be(p[0][1]) + be(p[0][0]) + be(p[1][1]) + be(p[1][0])  # x.c1||x.c0||y.c1||y.c0
n = vk["nPublic"]; assert len(pub) == n == len(vk["IC"]) - 1
fx = {"nPublic": n,
      "vk": {"alpha_g1": g1(vk["vk_alpha_1"]).hex(), "beta_g2": g2(vk["vk_beta_2"]).hex(),
             "gamma_g2": g2(vk["vk_gamma_2"]).hex(), "delta_g2": g2(vk["vk_delta_2"]).hex(),
             "ic": [g1(x).hex() for x in vk["IC"]]},
      "proof": {"a_neg": (be(pr["pi_a"][0]) + be((P - int(pr["pi_a"][1])) % P)).hex(),
                "b": g2(pr["pi_b"]).hex(), "c": g1(pr["pi_c"]).hex()},
      "public": [be(x).hex() for x in pub]}
json.dump(fx, open(sys.argv[4], "w"), indent=1)
if "--vk-rs" in sys.argv:
    arr = lambda h: "[" + ", ".join(str(x) for x in bytes.fromhex(h)) + "]"
    v = fx["vk"]
    open(sys.argv[sys.argv.index("--vk-rs") + 1], "w").write(
        "// GENERATED by scripts/kyc-fixture/convert_snarkjs.py from the RariMe query circuit vkey.\n"
        "use groth16_solana::groth16::Groth16Verifyingkey;\n\n"
        f"pub const N_PUBLIC: usize = {n};\n\n"
        f"pub const VK_IC: [[u8; 64]; {n+1}] = [\n" + "".join(f"    {arr(x)},\n" for x in v["ic"]) + "];\n\n"
        "pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {\n"
        f"    nr_pubinputs: N_PUBLIC,\n    vk_alpha_g1: {arr(v['alpha_g1'])},\n    vk_beta_g2: {arr(v['beta_g2'])},\n"
        f"    vk_gamme_g2: {arr(v['gamma_g2'])},\n    vk_delta_g2: {arr(v['delta_g2'])},\n    vk_ic: &VK_IC,\n}};\n")
